stages:
  training:
    cmd: python src/DiamondRegressor/pipeline/training_pipeline.py
    deps: 
      - config/config.yaml
      - src/DiamondRegressor/pipeline/training_pipeline.py
      - src/DiamondRegressor/components/data_ingestion.py
      - src/DiamondRegressor/components/data_preprocessing.py
      - src/DiamondRegressor/components/training.py
      - src/DiamondRegressor/components/model_finder.py
    params:
      - models.XgBoost.params.n_estimators
      - models.XgBoost.params.learning_rate
      - models.XgBoost.params.max_depth
      - models.XgBoost.params.min_child_weight
      - models.XgBoost.params.gamma
      - models.RandomForest.params.n_estimators
      - models.RandomForest.params.criterion
      - models.RandomForest.params.max_depth
      - models.RandomForest.params.min_samples_split
      - models.RandomForest.params.min_samples_leaf
      - models.RandomForest.params.bootstrap
      - models.DecisionTree.params.criterion
      - models.DecisionTree.params.max_depth
      - models.DecisionTree.params.min_samples_split
      - models.DecisionTree.params.min_samples_leaf
      - models.Lasso.params.alpha
      - models.Ridge.params.alpha
      - models.ElasticNet.params.alpha
      - models.ElasticNet.params.l1_ratio
    outs:
      - artifacts/data_ingestion/train_test.csv
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv
      - artifacts/preprocessing_object/preprocessor.pkl
      - artifacts/models