stages:

  data_ingestion:
    cmd: python src/DiamondRegressor/pipeline/stage_01_data_ingestion.py
    deps:
      - src/DiamondRegressor/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:

  data_preprocessing:
    cmd: python src/DiamondRegressor/pipeline/stage_02_data_preprocessing.py  
    deps:
      - src/DiamondRegressor/pipeline/stage_02_data_preprocessing.py  
      - config/config.yaml
    outs:
      - config/config.yaml

  model_training:
    cmd: python src/DiamondRegressor/pipeline/stage_03_model_training.py
    deps: 
    outs: