artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Akashr-18/Data_Store/raw/main/train_test.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  train_data_file_path: artifacts/data_ingestion/train.csv
  test_data_file_path: artifacts/data_ingestion/test.csv

data_preprocessing:
  root_dir: artifacts/preprocessing_object
  preprocessor_file_path: artifacts/preprocessing_object/preprocessor.pkl
  
model_training:
  root_dir: artifacts/models
  plot_dir: artifacts/plots
  plot_file_path: artifacts/plots/kmeans.png

training:
  root_dir: artifacts/models
  model_path: artifacts/models/model.pkl